# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Programme\Python38Code\FinishedProduct\WeChatFileClassification\MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 640)
        MainWindow.setMinimumSize(QtCore.QSize(940, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 760))
        MainWindow.setStyleSheet("*{font: 14pt \"微软雅黑\";}\n"
"QPushButton {\n"
"    color: black;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\';\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton[isPlaceholderText=true] {\n"
"    color: rgba(0, 0, 0, 0.6063);\n"
"}\n"
"\n"
"QPushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"QPushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"\n"
"QLineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"QLineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.wechatLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.wechatLabel_2.setMinimumSize(QtCore.QSize(0, 33))
        self.wechatLabel_2.setObjectName("wechatLabel_2")
        self.horizontalLayout_6.addWidget(self.wechatLabel_2)
        self.wechatlineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.wechatlineEdit_2.setMinimumSize(QtCore.QSize(0, 38))
        self.wechatlineEdit_2.setObjectName("wechatlineEdit_2")
        self.horizontalLayout_6.addWidget(self.wechatlineEdit_2)
        self.ChooseWeChatFile_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseWeChatFile_2.setMinimumSize(QtCore.QSize(120, 33))
        self.ChooseWeChatFile_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.ChooseWeChatFile_2.setObjectName("ChooseWeChatFile_2")
        self.horizontalLayout_6.addWidget(self.ChooseWeChatFile_2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outputLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel_2.setMinimumSize(QtCore.QSize(0, 33))
        self.outputLabel_2.setObjectName("outputLabel_2")
        self.horizontalLayout_4.addWidget(self.outputLabel_2)
        self.outputlineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.outputlineEdit_2.setMinimumSize(QtCore.QSize(0, 38))
        self.outputlineEdit_2.setObjectName("outputlineEdit_2")
        self.horizontalLayout_4.addWidget(self.outputlineEdit_2)
        self.ChooseOutPutFile_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseOutPutFile_2.setMinimumSize(QtCore.QSize(120, 33))
        self.ChooseOutPutFile_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.ChooseOutPutFile_2.setObjectName("ChooseOutPutFile_2")
        self.horizontalLayout_4.addWidget(self.ChooseOutPutFile_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.LogTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.LogTextBrowser.setObjectName("LogTextBrowser")
        self.gridLayout.addWidget(self.LogTextBrowser, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 20, -1, 40)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Start_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Start_2.setMinimumSize(QtCore.QSize(0, 40))
        self.Start_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.Start_2.setObjectName("Start_2")
        self.horizontalLayout_5.addWidget(self.Start_2)
        self.Cancel_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel_2.setMinimumSize(QtCore.QSize(0, 40))
        self.Cancel_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.Cancel_2.setObjectName("Cancel_2")
        self.horizontalLayout_5.addWidget(self.Cancel_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.VersionLabel = QtWidgets.QLabel(self.centralwidget)
        self.VersionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VersionLabel.setObjectName("VersionLabel")
        self.gridLayout.addWidget(self.VersionLabel, 7, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel_3.setMinimumSize(QtCore.QSize(0, 33))
        self.outputLabel_3.setObjectName("outputLabel_3")
        self.horizontalLayout_2.addWidget(self.outputLabel_3)
        self.SwitchButton = SwitchButton(self.centralwidget)
        self.SwitchButton.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.SwitchButton.setObjectName("SwitchButton")
        self.horizontalLayout_2.addWidget(self.SwitchButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.outputLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel_4.setMinimumSize(QtCore.QSize(0, 33))
        self.outputLabel_4.setObjectName("outputLabel_4")
        self.horizontalLayout_3.addWidget(self.outputLabel_4)
        self.DateSwitchButton = SwitchButton(self.centralwidget)
        self.DateSwitchButton.setMinimumSize(QtCore.QSize(0, 40))
        self.DateSwitchButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.DateSwitchButton.setObjectName("DateSwitchButton")
        self.horizontalLayout_3.addWidget(self.DateSwitchButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wechatLabel_2.setText(_translate("MainWindow", "微信文件夹路径："))
        self.ChooseWeChatFile_2.setText(_translate("MainWindow", "选择文件夹"))
        self.outputLabel_2.setText(_translate("MainWindow", "保存文件夹路径："))
        self.ChooseOutPutFile_2.setText(_translate("MainWindow", "选择文件夹"))
        self.Start_2.setText(_translate("MainWindow", "开始"))
        self.Cancel_2.setText(_translate("MainWindow", "取消"))
        self.VersionLabel.setText(_translate("MainWindow", "版本：1.4.0  "))
        self.outputLabel_3.setText(_translate("MainWindow", "是否保留原文件："))
        self.SwitchButton.setOnText(_translate("MainWindow", "是"))
        self.SwitchButton.setOffText(_translate("MainWindow", "否"))
        self.outputLabel_4.setText(_translate("MainWindow", "是否按文件日期对文件进行二次分类："))
        self.DateSwitchButton.setOnText(_translate("MainWindow", "是"))
        self.DateSwitchButton.setOffText(_translate("MainWindow", "否"))
from qfluentwidgets import SwitchButton
